### ISSUE TITLE
Localhost Error

### ISSUE THREAD

**Issue by AJajodia** [VoltaicHQ/Progress-Sheet-Updater#1]
After confirming my google account, the browser encounters a localhost error following a redirect from the google authorization page. No "token.pickle" is created.
![image](https://user-images.githubusercontent.com/53088267/102751837-8abeff00-4336-11eb-9d85-3c7082424f66.png)

**Comment by Y0ndaime** [comment]
Hey, are you logged into the same google account that you used to create the credentials.json?

**Comment by AJajodia** [comment]
Hey,

Turns out ms edge has weird issues with setting up localhost connections
with quickstart books.
