### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ilantt** [VoltaicHQ/Progress-Sheet-Updater#12]
`Traceback (most recent call last):`
`File "main.py", line 202, in <module>`
`File "logging\config.py", line 71, in fileConfig`
`File "logging\config.py", line 104, in _create_formatters`
`File "configparser.py", line 958, in __getitem__`
`KeyError: 'formatters'`
`[8560] Failed to execute script main`

Started happening after my PC crashed while Kovaak's and the tool were open. Tried verifying Kovaak's files and reinstalling (and updating to 1.1) the tool.

**Comment by MingoDynasty** [comment]
Do you have a `logging.conf` file somewhere?

**Comment by ilantt** [comment]
[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter,consoleFormatter

[logger_root]
level=NOTSET
handlers=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=consoleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=simpleFormatter
args=('debug.log', 'w')

[formatter_simpleFormatter]
format=%(asctime)s | %(levelname)s | %(name)s | %(message)s

[formatter_consoleFormatter]
format=%(asctime)s | %(message)s

**Comment by ilantt** [comment]
I literally did nothing and it somehow fixed itself. I guess... Uhm... _Thanks?.._
