### ISSUE TITLE
Progress updater 1.0 and 1.11

### ISSUE THREAD

**Issue by tonyhuang219** [VoltaicHQ/Progress-Sheet-Updater#13]
I've been using the progress updater for about two weeks without any issue. But today, when I try using the progress updater, it crashes immediately. I have not made any changes to the linked spreadsheet.

![error1](https://user-images.githubusercontent.com/40710752/105898645-ae393180-5fe7-11eb-9659-64000ee3360f.PNG)
![error2](https://user-images.githubusercontent.com/40710752/105898655-b1342200-5fe7-11eb-94d4-191cabc6c37e.PNG)

**Comment by Y0ndaime** [comment]
Hey, that error is odd since it is caused by an invalid format in the blacklist. Did you try running the program again today? Maybe someone was making changes to the blacklist as you were trying to run it.
