### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by AverytheFurry** [VoltaicHQ/Progress-Sheet-Updater#14]
Hey, I wasn't quite sure where to ask this, so I thought here might work. I was curious if there would be any hope that a linux version could be built! Thank you.

**Comment by Y0ndaime** [comment]
Hey, I don't use linux myself, but i found this https://stackoverflow.com/questions/13933169/how-to-execute-python-file-in-linux and you can probably use that by downloading the source and not the release.

**Comment by AverytheFurry** [comment]
> Hey, I don't use linux myself, but i found this https://stackoverflow.com/questions/13933169/how-to-execute-python-file-in-linux and you can probably use that by downloading the source and not the release.

Thank you, will try this!
