### ISSUE TITLE
Authorization Failure

### ISSUE THREAD

**Issue by brandonwalz** [VoltaicHQ/Progress-Sheet-Updater#17]
I'm trying to setup a new Google Cloud Platform project and failing to do so. I've followed the instructions (written and video) a couple of times but still run into the same error when I first run the updater and arrive at (what would be) the authorization screen. I'm instead met with: 
![image](https://user-images.githubusercontent.com/11547959/115482462-bc7c9f80-a21c-11eb-9ac7-517515925f06.png)

Eventually I realized I had an old credentials and token files on a different PC (and the old Google project was still there), and I've used those successfully so I'm able to use the application. I saw in discord that a few other users were having this issue and didn't see a resolution. Thanks!

**Comment by Y0ndaime** [comment]
For anyone still getting this error make sure to check the comments of the video. The pinned comment contains a fix
