### ISSUE TITLE
Failed to execute script main error when running 1.22

### ISSUE THREAD

**Issue by natdempk** [VoltaicHQ/Progress-Sheet-Updater#21]
👋 Hi, I'm trying to use this tool for the first time, and with the latest release I got this error trying to run the program. I've gone through the Google Cloud setup + antivirus allowlisting, and get this error when running the program. 

![image](https://user-images.githubusercontent.com/1648519/118372770-2ae52100-b581-11eb-83a7-daccb786b52d.png)

Let me know if there's any other helpful debug info I can provide, happy to help out. I'm guessing something about the path resolution is not computing the path for `logging.conf` correctly. 

cc: @Y0ndaime since I saw you cut a release of this recently.

**Comment by Y0ndaime** [comment]
Fixed the bug, for more info look here https://stackoverflow.com/questions/404744/determining-application-path-in-a-python-exe-generated-by-pyinstaller Thank you for letting me know
