### ISSUE TITLE
Can you update the spreadsheet and tracker for Voltaic 2.0's new benchmark?

### ISSUE THREAD

**Issue by Xyde** [VoltaicHQ/Progress-Sheet-Updater#23]
Voltaic 2.0 includes new values for ranks like Iron and Bronze, and certain values have changed for other ranks.

**Comment by Y0ndaime** [comment]
The newest sheet is this https://docs.google.com/spreadsheets/d/1yHj87rQNW2WsuH24UoKZajNwNpI6CVyUjR3AwBMbnnY/edit#gid=1324419980 .
If you want to update to it just paste the new link in and it should work. If you are asking for the sheet to be updated, what values for the iron/bronze rank have you seen (if they arent on that sheet already).

**Comment by Xyde** [comment]
Yeah. The sheet you linked in the readme in about and getting started is not the same sheet you just linked. (Like patts voltaic easy in the old ver is 69 silver but 80 silver in the new one)

To update it (i have the older version), do I need to make a new copy and redo all the steps?

**Comment by Y0ndaime** [comment]
Thanks for pointing out the outdated link in the readme I will fix it. If you want to update the sheet you just have to create a copy of the new one and then replace the old link with the new one in the config. If you want to update to a new version of the updater it is enough to replace the existing versions of the files with the new ones.
