### ISSUE TITLE
Error when launching the exe program after authentication

### ISSUE THREAD

**Issue by Yikizi** [VoltaicHQ/Progress-Sheet-Updater#28]
I open it, press "finish" and I get prompted with:
2022-04-17 19:55:29,454 | Sheets API error: Unable to parse range: Novice!C3:C14
Can anybody help me with this?

**Comment by NicholasDHarrison** [comment]
> I open it, press "finish" and I get prompted with: 2022-04-17 19:55:29,454 | Sheets API error: Unable to parse range: Novice!C3:C14 Can anybody help me with this?

Hey I had a similar issue, please go to the "tech" channel in their discord. For me it was an outdated Benchmark sheet, get a copy of the new one. Then just go ahead and run the .exe and plug in the new sheet's url. Hope this helps!
