### ISSUE TITLE
Getting virus warnings

### ISSUE THREAD

**Issue by elloot** [VoltaicHQ/Progress-Sheet-Updater#3]
When I'm trying to download the latest version from Releaes, I get a notification from Bitdefender saying it blocked the download because of a trojan. The threat name is Trojan.GenericKD.35816057 and I get it every time I try to download the tool. I could download it before, I even set it up and used it for about a day and really enjoyed it, but then Bitdefender removed it. I'm happy to provide any further information that I can if necessary.

**Comment by jriall** [comment]
I'm having the same issue - I cannot even run the exe file after downloading again as my virus software automatically deletes it.

**Comment by Y0ndaime** [comment]
Hey,
Most Antivirus programs will treat the application as a virus because it does not have a license. The source code is public so you can check it yourself. If you want to run the application you will have to whitelist it in your antivirus program.

**Comment by elloot** [comment]
I think I whitelisted it when I first downloaded it, but then it was randomly removed. Don't get me wrong, I don't believe you actually included some sort of trojan in the program, I do want to use it. At the moment I can't download it though, I have tried adding an exclusion in Bitdefender but it still doesn't allow me to download it.

**Comment by MingoDynasty** [comment]
@Y0ndaime Can you try re-compiling the project to .exe? When I used Pyinstaller on my local environment, following the existing main.spec, I generated an .exe file that passed BitDefender scan successfully, according to virustotal.com.

**Comment by elloot** [comment]
I also get no issues when building the .exe myself.

**Comment by elloot** [comment]
Update: I do infact get an issue, when I try to run the executable my console fills with text and instantly closes. I am new to Python but managed to gather that you build executables with pyinstaller. `pyinstaller --onefile main.py -n ProgressSheetUpdate` is the command I used to build (Bitdefender still won't allow me to call it "ProgressSheetUpdater").

**Comment by MingoDynasty** [comment]
@elloot Try running the executable file via command prompt so you can see the output instead of the CLI window immediately closing.

Note that the `main.spec` file specifies some libraries (i.e. google api python client) that aren't automatically captured by your `pyinstaller` command.

**Comment by elloot** [comment]
@MingoDynasty thanks, I will try running it through the command line later. How do I make sure that those libraries get captured when I run the command?

**Comment by jriall** [comment]
Whitelisting the directory in MalwareBytes worked fine for me.

**Comment by MingoDynasty** [comment]
@elloot I'm not sure, I haven't tried without using the `main.spec` file. But maybe @Y0ndaime can fill us in.

**Comment by riddbtw** [comment]
FYI I [submitted a PR](https://github.com/VoltaicHQ/Progress-Sheet-Updater/pull/8) to resolve this issue.  I didn't realize this issue was open or I would've linked the PR.

**Comment by elloot** [comment]
Great! Let's hope it get's merged soon, I'm growing tired of manually updating my sheet 😄.

**Comment by nickofc** [comment]
> Great! Let's hope it get's merged soon, I'm growing tired of manually updating my sheet 😄.

You can simply run the script with python. 

1. Install the latest version of python (version 3).
2. Download the repository and unpack it (https://github.com/VoltaicHQ/Progress-Sheet-Updater/archive/main.zip).
3. Run cmd console where you extracted the files.
4. Type in the console cmd **py main.py** (do not forget to fill in the data in config file - description in the main guide).

**Comment by nickofc** [comment]
>Great! Let's hope it get's merged soon, I'm growing tired of manually updating my sheet 😄.

@elloot
You can simply run the script with python.

1. Install the latest version of python (version 3).
2. Download the repository and unpack it (https://github.com/VoltaicHQ/Progress-Sheet-Updater/archive/main.zip).
3. Run cmd console where you extracted the files.
4. Type in the console:
pip install -r requirements.txt 
cmd py main.py

Do not forget to fill in the data in config file - description in the main guide.

**Comment by elloot** [comment]
@nickofc thank you, it's kind of odd that it works fine to start the program from the dev files but building an executable causes problems. It's probably just because of my inexperience with Python though 😅. Nevertheless, it works now and that's all I wanted. I think I will keep this issue open until the problem has been fixed for the dist-version as well, though.

**Comment by Y0ndaime** [comment]
Hey, we just released 1.1 and are using a GitHub workflow for releases now. I hope that fixes this problem, if it does not you will have to whitelist the file in your antivirus program.
