### ISSUE TITLE
Issue when starting program for aimlab

### ISSUE THREAD

**Issue by zekromblitzi** [VoltaicHQ/Progress-Sheet-Updater#30]
Whenever I open the app, I get this error and it closes, any possible fixes?

![image](https://user-images.githubusercontent.com/63116066/167731492-5e2ffdca-2971-4069-8c98-88a3007a38d8.png)

**Comment by ezollo** [comment]
I am getting the same problem as zekromblitzi

**Comment by Y0ndaime** [comment]
Hi, due to an update to the AL Benches you will need to edit the values in the config.json to match the ones in this picture https://media.discordapp.net/attachments/657892003128016906/971470028174135356/unknown.png . It's also pinned in #tech in the discord.

**Comment by Y0ndaime** [comment]
Closing for now, if you need further help feel free to reopen this issue

**Comment by Hifumii** [comment]
I get the same exact error and I checked to see if the values in the config.json file were correct and they are. The updater worked fine for me until today. I would really appreciate any help.
I think it may have to do with a change in the spreadsheet removing spheretrack from the scenarios.
