### ISSUE TITLE
Configurator Loop

### ISSUE THREAD

**Issue by Cironde** [VoltaicHQ/Progress-Sheet-Updater#39]
i followed the instructions, ran the progressupdater file and got the pickle token but when i run the progress updater again it runs the configurator every time. it also does not populate the benchmark sheet.
i don't know if this is the place to ask for help with this or not but thought i'd give it a shot and maybe someone could at least point me in the right direction?  thanks.

update: i left the updater running while using kovaak and it says that it was updating each time i finished a task.  i just have no idea what it updated because my actual sheet was not.

**Comment by Y0ndaime** [comment]
Hey, ping me in the #tech channel of the discord and ill take a look, it would be nice if you could attach your config file as well

**Comment by Y0ndaime** [comment]
Solved in discord, issue was that the wrong scenarios were played
