### ISSUE TITLE
csv error line contains NUL 

### ISSUE THREAD

**Issue by yuse4c** [VoltaicHQ/Progress-Sheet-Updater#42]
![image_2024-02-09_181714950](https://github.com/VoltaicHQ/Progress-Sheet-Updater/assets/159598620/58c05c81-7a2e-4b83-b124-d897b5f92146)

**Comment by uzeboster** [comment]
Same

**Comment by yuse4c** [comment]
> Same
my solution was to delete the files in the stats folder hope this helps!

**Comment by Y0ndaime** [comment]
This error occurs if there is a faulty stat file in your stats folder. To resolve it you need to remove the faulty file. You can either do this via trial&error or by removing all stats files.
