### ISSUE TITLE
Updater tool crashes after few seconds.

### ISSUE THREAD

**Issue by BugAndAHalf11** [VoltaicHQ/Progress-Sheet-Updater#43]
It only opens and I put the link of my progress sheet inside the link box then I click finish and everything seems fine and I start playing Kovaacks but It crashes after a few seconds. I've tried removing all files and fresh installing the update but nothing seems to work its also in the whitelist of my antivirus and tried running as admin but still crashing It was working fine yesterday but today it stopped working all of a sudden,
![111111111111111](https://github.com/VoltaicHQ/Progress-Sheet-Updater/assets/130006547/0754e9c5-bf16-42d7-90ce-ed03ac685388)

**Comment by yuse4c** [comment]
i had this too my solution was to delete the files in the stats folder

**Comment by BugAndAHalf11** [comment]
> i had this too my solution was to delete the files in the stats folder

Well this is the only thing that works thanks for the reply sir bless ya....
