### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Freebandstv** [VoltaicHQ/Progress-Sheet-Updater#9]
Traceback (most recent call last):
  File "main.py", line 149, in <module>
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 19 (char 20)
[20744] Failed to execute script main

**Comment by MingoDynasty** [comment]
Check your `config.json` file and ensure that it is properly formatted.

@Y0ndaime we might consider wrapping this `config = json.load(open(config_file, 'r'))` inside a try/except block to more gracefully handle improperly formatted JSON files.

**Comment by Y0ndaime** [comment]
@MingoDynasty Yeah i agree, the GUI should handle most issues but better errorhandling never hurts

**Comment by MingoDynasty** [comment]
Even still, the GUI needs the initial `config.json` file to load properly in order to pre-fill the GUI selections.

**Comment by Freebandstv** [comment]
Is it because the game is installed on my F: Drive rather than my C: Drive?

**Comment by MingoDynasty** [comment]
The default `config.json` file is properly formatted. If you post your config file then we can double check it for you.

**Comment by ExecutedOnce** [comment]
Had exact same issue, replaced the install and ran it (let it access drive) before modifying config. 
My most likely mistake was copying the path and not including double backslashes like it has by default.
F:\\steam\\steamapps\\common\\FPSAimTrainer\\FPSAimTrainer\\stats

**Comment by MingoDynasty** [comment]
Backslashes act as an escape character, so in strings a "\\" is interpreted as a single backslash.

The other option, you can use forward slashes. So e.g. `F:/steam/steamapps/common/FPSAimTrainer/FPSAimTrainer/stats`
